app/shoes/urls.py
from django.urls import path, include
from shoes import views


app_name = 'main'

urlpatterns = [
    path('', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('products/', views.products_page, name='products'),
    path('product/', include([
        path('create/', views.product_create_page, name='product_create'),
        path('update/<int:pk>/', views.product_update_page, name='product_update'),
        path('delete/<int:pk>/', views.product_delete, name='product_delete'),
    ]))
]

app/shoes_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shoes.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/shoes/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'categories'

    def __str__(self):
        return self.name


class OrderItems(models.Model):
    order = models.ForeignKey('Orders', models.DO_NOTHING)
    product = models.ForeignKey('Products', models.DO_NOTHING)
    amount = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'order_items'


class Orders(models.Model):
    created_date = models.DateField()
    delivered_date = models.DateField()
    pick_point = models.ForeignKey('PickPoints', models.DO_NOTHING)
    user = models.ForeignKey('Users', models.DO_NOTHING)
    code = models.IntegerField(blank=True, null=True)
    status = models.ForeignKey('StatusOrder', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'orders'


class PickPoints(models.Model):
    zipcode = models.IntegerField()
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    builder = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pick_points'

    def __str__(self):
        return f'{self.zipcode}, {self.city}, {self.street}'


class Producers(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'producers'

    def __str__(self):
        return self.name


class Products(models.Model):
    articale = models.CharField(max_length=50, verbose_name='Артикул')
    name = models.CharField(max_length=255, verbose_name='Название')
    unit = models.ForeignKey('Units', models.DO_NOTHING, verbose_name='Единица измерения')
    price = models.IntegerField(verbose_name='Цена')
    provider = models.ForeignKey('Providers', models.DO_NOTHING, verbose_name='Поставщик')
    producer = models.ForeignKey(Producers, models.DO_NOTHING, verbose_name='Производитель')
    category = models.ForeignKey(Categories, models.DO_NOTHING, verbose_name='Категория')
    sale = models.IntegerField(blank=True, null=True, verbose_name='Скидка')
    amount = models.IntegerField(verbose_name='Количество')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(
        upload_to='images/',
        blank=True,
        null=True,
        verbose_name='Картинка',
        help_text='Загрузите изображение (JPG, PNG)',
    )

    class Meta:
        managed = False
        db_table = 'products'

    @property
    def final_price(self):
        if self.sale and self.sale > 0:
            return self.price * (1 - self.sale / 100)
        return self.price

    def __str__(self):
        return f'{self.articale} | {self.name}'


class Providers(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'providers'

    def __str__(self):
        return self.name


class Roles(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'roles'

    def __str__(self):
        return self.name


class StatusOrder(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'status_order'

    def __str__(self):
        return self.name


class Units(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'units'

    def __str__(self):
        return self.name


class Users(models.Model):
    role = models.ForeignKey(Roles, models.DO_NOTHING)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255, blank=True, null=True)
    login = models.CharField(max_length=255)
    password = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'users'

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.middle_name}'

app/shoes/forms.py
from django import forms
from django.contrib.auth.models import User
from shoes.models import Products


class LoginForm(forms.ModelForm):
    """Форма авторизации"""

    class Meta:
        model = User
        fields = ['username', 'password']
        labels = {
            'username': 'Логин',
            'password': 'Пароль',
        }
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите логин'
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите пароль'
            }),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class ProductForm(forms.ModelForm):
    """Форма добавление/редактирования товара"""

    class Meta:
        model = Products
        fields = '__all__'

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

app/shoes/views.py
import copy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator

from shoes.forms import LoginForm, ProductForm
from shoes.models import Products, Providers, Users


def login_page(req):
    """Авторизация в системе"""

    if req.method == 'POST':
        form = LoginForm(req.POST)

        username = req.POST.get('username')
        password = req.POST.get('password')
        user = authenticate(req, username=username, password=password)
        if user is not None:
            login(req, user)
            messages.success(req, f'Добро пожаловать, {user.get_full_name() or user.username}!')
            return redirect('main:products')
        else:
            messages.error(req, 'Неверное имя пользователя или пароль.')
    else:
        form = LoginForm()

    return render(
        request=req,
        template_name='login.html',
        context={
            'title': 'Авторизация',
            'form': form,
        }
    )


def logout_page(req):
    """Выход из системы"""

    logout(req)
    messages.success(req, 'Вы успешно вышли из системы.')
    return redirect('main:login')


def get_user_role(user):
    if not user.is_authenticated:
        return 'guest'
    if user.is_superuser:
        return 'admin'
    return 'user'


def products_page(req):
    """Каталог товаров"""

    user_role = get_user_role(req.user)
    providers = Providers.objects.all()

    products = Products.objects.select_related('category', 'provider', 'producer', 'unit')

    if user_role in ['manager', 'admin']:
        search_value = req.GET.get('search', '')
        if search_value:
            products = products.filter(
                Q(name__icontains=search_value) |
                Q(description__icontains=search_value) |
                Q(provider__name__icontains=search_value) |
                Q(producer__name__icontains=search_value)
            )

        provider_filter = req.GET.get('provider', '') 
        if provider_filter:
            products = products.filter(provider__name=provider_filter)

        sort_by = req.GET.get('sort', 'name-asc')
        match sort_by:
            case 'name-asc':
                products = products.order_by('name')
            case 'name-desc':
                products = products.order_by('-name')
            case 'price-asc':
                products = products.order_by('price')
            case 'price-desc':
                products = products.order_by('-price')
            case 'amount-asc':
                products = products.order_by('amount')
            case 'amount-desc':
                products = products.order_by('-amount')
            case _:
                products = products.order_by('name')
        
    else:
        search_value = ''
        provider_filter = ''
        sort_by = ''

    paginator = Paginator(products, 10)
    page_num = req.GET.get('page')
    page_obj = paginator.get_page(page_num)

    return render(
        request=req,
        template_name='products.html',
        context={
            'title': 'Каталог товаров',
            'user': req.user,
            'user_role': user_role,
            'page_obj': page_obj,
            'providers': providers,
            'sort_by': sort_by,
            'search_value': search_value,
            'provider_filter': provider_filter,
        }
    )


@login_required
def product_create_page(req):
    """Добавление товара (только для администратора)"""

    user_role = get_user_role(req.user)
    if user_role not in 'admin':
        messages.info(req, 'Действие только для администратора!')
        return redirect('main:products')

    if req.method == 'POST':
        form = ProductForm(req.POST, req.FILES)
        if form.is_valid():
            form.save()
            messages.success(req, 'Товар добавлен успешно!')
            return redirect('main:products')
    else:
        form = ProductForm()

    return render(
        request=req,
        template_name='product.html',
        context={
            'title': 'Добавление товара',
            'form': form,
        }
    )


@login_required
def product_update_page(req, pk):
    """Редактирование товара (только для администратора)"""

    user_role = get_user_role(req.user)
    if user_role not in 'admin':
        messages.info(req, 'Действие только для администратора!')
        return redirect('main:products')

    product = get_object_or_404(Products, pk=pk)
    old_product = copy.deepcopy(product)

    if req.method == 'POST':
        form = ProductForm(req.POST, req.FILES, instance=product)
        if form.is_valid():
            # Удаление фото при добавление новой или очистке старой
            if ('image' in req.FILES and old_product.image) or req.POST.get('image-clear') == 'on':
                old_product.image.delete()
            form.save()
            messages.success(req, 'Товар обновлен успешно!')
            return redirect('main:products')
    else:
        form = ProductForm(instance=product)

    return render(
        request=req,
        template_name='product.html',
        context={
            'title': 'Редактирование товара',
            'form': form,
        }
    )


@login_required
def product_delete(req, pk):
    """Удаление товара (только для администратора)"""

    user_role = get_user_role(req.user)
    if user_role not in 'admin':
        messages.info(req, 'Действие только для администратора!')
        return redirect('main:products')

    product = get_object_or_404(Products, pk=pk)
    product.delete()
    messages.success(req, 'Товар успешно удален!')
    return redirect('main:products')

app/shoes/templates/base.html
{% load static %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{title}}{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
</head>

{% block style %}
<style>
    .form-control:focus {
        border-color: #00FA9A !important;
    }
</style>
{% endblock %}
<body>
    <div class='container d-flex flex-column gap-4 py-4'> 
        {% bootstrap_messages %} 
        {% block content %}{% endblock %}
    </div>
    {% block script %}{% endblock %}
</body>
</html>

app/shoes/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<img src="{% static 'img/logo.png' %}" alt="Логотип" style="object-fit: contain; width: 150px;">
<div class="card" style="max-width: 500px;">
    <div class="card-header">
        <h1 class="card-title">{{ title }}</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{field.id_for_label}}" class="form-label">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger">{{ field.errors }}</div>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn" style="background: #00FA9A;">Войти</button>
        </form>
        <hr>
        <div class="d-flex flex-column gap-3">
            <a href="{% url 'main:products' %}">Гость</a>
        </div>
    </div>
</div>

{% endblock %}

app/shoes/templates/product.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
    <div>
        <a href="{% url 'main:products' %}" class="btn btn-outline-secondary mb-3">Назад</a>
        <h1>{{ title }}</h1>
        <hr>
        <form method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn" style="background: #00FA9A;">Сохранить</button>
        </form>
    </div>
{% endblock %}

app/shoes/templates/products.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<style>
    .list-group-item {
        background-color: transparent !important;
    }

    .big-sale {
        background-color: #2E8B57 !important;
    }

    .empty {
        background-color: lightblue !important;
    }

</style>
{% endblock %}

{% block content %}
    {% if user_role not in 'guest' %}
        <div class="d-flex justify-content-end align-items-center gap-3 bg-dark p-3 rounded-4">
            {% if user_role in 'admin' %}
                <a href="{% url 'main:product_create' %}" class="btn btn-light" style="margin-left: 0; margin-right: auto;">Добавить товар</a>
            {% endif %}
            <div class="text-light">{{ user }}</div>
            <a href="{% url 'main:logout' %}" class="btn btn-light">Выход</a>
        </div>

        <div class="d-flex align-items-center p-3 bg-light rounded-4">
            <form class="d-flex gap-2 w-100">
                {% csrf_token %}
                <div class="form-floating col-3">
                    <input type="text"
                        class="form-control" 
                        id="search" 
                        name="search" 
                        placeholder="Поиск"
                        value="{{ search_value }}">
                    <label for="search">Поиск</label>
                </div>
                <div class="form-floating col-3">
                    <select class="form-select" id="sort" name="sort">
                        <option value="name-asc" {% if sort_by == 'name-asc' %}selected{% endif %}>А-Я</option>
                        <option value="name-desc" {% if sort_by == 'name-desc' %}selected{% endif %}>Я-А</option>
                        <option value="price-asc" {% if sort_by == 'price-asc' %}selected{% endif %}>По возрастанию цены</option>
                        <option value="price-desc" {% if sort_by == 'price-desc' %}selected{% endif %}>По убыванию цены</option>
                        <option value="amount-asc" {% if sort_by == 'amount-asc' %}selected{% endif %}>По возрастанию кол-ва</option>
                        <option value="amount-desc" {% if sort_by == 'amount-desc' %}selected{% endif %}>По убыванию кол-ва</option>
                    </select>
                    <label for="sort">Сортировка</label>
                </div>
                <div class="form-floating col-3">
                    <select class="form-select" id="provider" name="provider">
                        <option value="">Все поставщики</option>
                        {% for provider in providers %}
                            <option value="{{ provider.name }}" {% if provider_filter == provider.name %}selected{% endif %}>
                                {{ provider.name }}
                            </option>
                        {% endfor %}
                    </select>
                    <label for="provider">Поставщик</label>
                </div>
                <button type="reset" class="btn btn-danger">Сброс</button>
            </form>
        </div>
    {% endif %}

    <div class="d-flex flex-column gap-2">
        {% for product in page_obj %}
            <div class="card rounded-3 {% if product.sale > 15 %}big-sale{% endif %} {% if product.amount == 0 %}empty{% endif %}">
                <div class="row card-body">
                    <div class="col-4">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/picture.png' %}{% endif %}" 
                             alt="Фото" style="width: 100%; object-fit: contain;">
                    </div>
                    <div class="col-6">
                        <h2 class="h3 mb-3">{{ product.category.name }} | {{ product.name }}</h2>
                        <ul class="list-group">
                            <li class="list-group-item">Описание товара: {{ product.description }}</li>
                            <li class="list-group-item">Производитель: {{ product.producer.name }}</li>
                            <li class="list-group-item">Поставщик: {{ product.provider.name }}</li>
                            <li class="list-group-item">Цена:
                                {% if product.sale and product.sale > 0 %}
                                    <span style="color: black">{{ product.final_price|floatformat:0 }}</span>
                                    <span style="color: red"><s>{{ product.price }}</s></span>
                                {% else %}
                                    {{ product.price }}
                                {% endif %}
                            </li>
                            <li class="list-group-item">Единица измерения: {{ product.unit.name }}</li>
                            <li class="list-group-item">Количество на складе: {{ product.amount }}</li>
                        </ul>
                    </div>
                    <div class="col-2 text-center">
                        <div class="border rounded-3 p-2 mb-3">
                            <div>Скидка</div>
                            <div>{{ product.sale }}%</div>
                        </div>
                        {% if user_role in 'admin' %}
                            <div class="d-flex flex-column gap-2">
                                <a href="{% url 'main:product_update' product.id %}">Редактировать</a>
                                <a href="{% url 'main:product_delete' product.id %}">Удалить</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <div>Пусто</div>
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        <div class="d-flex gap-3 mt-4">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}&search={{ search_value }}&sort={{ sort_by }}&provider={{ provider_filter }}"
                   class="btn btn-light">
                    Предыдущая
                </a>
            {% endif %}
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&search={{ search_value }}&sort={{ sort_by }}&provider={{ provider_filter }}"
                   class="btn btn-light">
                    Следующая
                </a>
            {% endif %}
        </div>
    {% endif %}
{% endblock content %}

{% block script %}
<script>
    // Курсор в конец при вводе
    const setFocusToEnd = (element) =>  {
        element.focus();
        const length = element.value.length;
        element.setSelectionRange(length, length);
    }

    setFocusToEnd(document.querySelector('#search'))

    // Поиск, сортировка, фильтрация
    const updateFilters = () => {
        const search = document.querySelector('#search').value;
        const sort = document.querySelector('#sort').value;
        const provider = document.querySelector('#provider').value;

        const params = new URLSearchParams();
        if (search) params.set('search', search);
        if (sort) params.set('sort', sort);
        if (provider) params.set('provider', provider);
        params.set('page', '1');

        window.location.href = '?' + params.toString();
    };

    let tID;
    document.querySelector('#search').addEventListener('input', (e) => {
        clearTimeout(tID);
        tID = setTimeout(updateFilters, 500);
    });

    document.querySelector('#sort').addEventListener('change', updateFilters);
    document.querySelector('#provider').addEventListener('change', updateFilters);

    // Сброс
    document.querySelector('form').addEventListener('reset', (e) => {
        const params = new URLSearchParams();
        params.set('search', '');
        params.set('sort', '');
        params.set('provider', '');
        params.set('page', '1');

        window.location.href = '?' + params.toString();
    });
</script>
{% endblock %}